### PR TITLE
Added object structure for MJML Content to ensure api library works

### PR DESCRIPTION
**Pull request by tiger5226**
Added object structure for MJML Content to ensure api library works with `template/:id/detailcontent`

### CODE REVIEW

**Comment by tiger5226** [comment]
Can this be merged in? I would like to not have a fork of the repo.

**Comment by mskochev** [comment]
Hello, sorry for the big delay. Thanks a lot for your bug fix. We've reviewed your pull request. In fact the first commit looks good, but in the second commit (from Nov 7) you are changing the name of the library which is not good. Please can you remove it, so we can merge only the first commit?

Kind regards,
Martin

**Comment by tiger5226** [comment]
Abosolutely! My apologies I had to create my own repo to deploy the api with the fix. I will remove it and force push.

**Comment by tiger5226** [comment]
actually I will create a new branch off of the original commit and create a new PR.

**Comment by tiger5226** [comment]
I created a new branch with just that change and created a new PR https://github.com/mailjet/mailjet-apiv3-go/pull/52

**Comment by mskochev** [comment]
Thanks a lot for your fix. It is merged.

**Pull request closed without merging**
