### PR TITLE
mailjet: refactor http client

### LINKED ISSUE #20: mailjet-apiv3-go: refactor HTTP client
Now when send request using `mailjet.Client` in implemntation of methods (List, ListData, Get, GetData and etc.) have duplication of code. For example: `resp.body.Close()` and `json.NewDecoder(...).Decode(...)` are used a total of 30 times. We can avoid this unnecessary code as extract this logic in one place. Than code will be more clear.

### PR DESCRIPTION
**Pull request by EmilGeorgiev**
fixes #20

I created wrapper of HTTP client and extract all duplicated logic in one place. As result of this, code snippets like: 

``` go
resp, err := mj.doRequest(req)

if err != nil {     
    return count, total, err        
}

if resp == nil {        
    return count, total, fmt.Errorf("empty response")       
}

defer resp.Body.Close()     

return readJSONResult(resp.Body, res)
```

are replaced with simple one line:

``` go
mj.client.Send(req).Read(resp).Call()
```

@donatj @arnaudbreton

### CODE REVIEW

**Comment by Zhivko-Mailjet** [comment]
Hi @EmilGeorgiev 

It’s a nice refactoring, but there are few mandatory points missing:

1) The HTTP setter (which is required for Google App Engine) example : https://cloud.google.com/appengine/docs/go/mail/mailjet#sending_mail)
2) Reset method to clear the httpClient before or after any use (it will provide an error if you do a "Delete" request after "Read" or  "With")
3) Json is different for the send API. readJSONResult method should be rewritten to something like this: https://gist.github.com/kgilonne/1dea5323c29ee347eb9759c1ab3a2a12
4) resp.Body is already closed here : https://github.com/EmilGeorgiev/mailjet-apiv3-go/blob/mailjet_refactor_http_client/core.go#L233 in case of an error returned by Do(req)
and here: https://github.com/EmilGeorgiev/mailjet-apiv3-go/blob/mailjet_refactor_http_client/core.go#L246 in case of a bad StatusCode.

In order for us to validate the changes, please commit the above mentioned corrections. Thanks again for your contribution!

**Comment by EmilGeorgiev** [comment]
Hi @Zhivko-Mailjet,

Thanks for your suggestions, I fixed all of them.

  1. Setter for HTTP is added.
  2.  Reset method to clear ```httpClient``` after any use.
  3. I rewrite method ```readJSONResult``` to  https://gist.github.com/kgilonne/1dea5323c29ee347eb9759c1ab3a2a12
  4. Remove unnecessary closing of response body here  https://github.com/EmilGeorgiev/mailjet-apiv3-go/blob/mailjet_refactor_http_client/core.go#L233 and here  https://github.com/EmilGeorgiev/mailjet-apiv3-go/blob/mailjet_refactor_http_client/core.go#L246

**Comment by oranj** [comment]
@donatj?

**Comment by Zhivko-Mailjet** [comment]
Hi @EmilGeorgiev ,

Thanks for making the changes. We noticed one more thing - the response from our API is not printed (e.g. sender's email address and message ID). Could you include this ?

**Comment by EmilGeorgiev** [comment]
Hi Guys,

I fix bug and now Send API return recipient's email and message ID. Problem was in parameter ```res``` which I pass to method ```Read(res)```. It was ```nil```:

BEFORE

```go
// SendMail send mail via API.
func (mj *Client) SendMail(data *InfoSendMail) (res *SentResult, err error) {
	...
	_, _, err = mj.client.Send(req).With(headers).Read(res).Call()

	return res, err
}
```

NOW:

```go
// SendMail send mail via API.
func (mj *Client) SendMail(data *InfoSendMail) (res *SentResult, err error) {
	...
	_, _, err = mj.client.Send(req).With(headers).Read(&res).Call()

	return res, err
}
```

**Pull request merged**
